### ISSUE TITLE
Error after migration to Nautobot V2.1.0

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot-app-device-onboarding#144]
### Environment
* Python version:  3.11.7
* Nautobot version:  81fc9bf35347 (v2.1.0)
* nautobot-device-onboarding version:  3.0.1

### Expected Behavior
Initalizing nautobot-device-onboarding suold run without error

### Observed Behavior
A Traceback is shown in LOG:

```
Traceback (most recent call last):
  File "/usr/local/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/cli/__init__.py", line 53, in main
    run_app(
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/runner/runner.py", line 297, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 202, in handle
    pre_migrate_apps = pre_migrate_state.apps
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/state.py", line 208, in apps
    return StateApps(self.real_apps, self.models)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/state.py", line 277, in __init__
    raise ValueError("\n".join(error.msg for error in errors))
ValueError: The field nautobot_device_onboarding.OnboardingTask.role was declared with a lazy reference to 'dcim.devicerole', but app 'dcim' doesn't provide model 'devicerole'.
The field nautobot_device_onboarding.OnboardingTask.site was declared with a lazy reference to 'dcim.site', but app 'dcim' doesn't provide model 'site'.
```

### Steps to Reproduce
1. Upgrade Nautobot from 1.4.10 with nautobot-device-onboarding installed to Nautobot v2.1.0
2. Start Nautobot
3.

**Comment by jifox** [comment]
I noticed, that I had not enabled the onboarding plugin during data migration. I restartet (using v1 data) the migration with onboarding plugin enabled and it gives no error.
