### ISSUE TITLE
Upgrade Nautobot from 1.6.5 to 2.1.0, perform server migration fails with traceback on onboarding plugin

### ISSUE THREAD

**Issue by dbbtuss** [nautobot/nautobot-app-device-onboarding#147]
### Environment
* Python version:  3.8
* Nautobot version:  2.1
* nautobot-device-onboarding version:  3.0.1

### Expected Behavior
Successful migration

### Observed Behavior
Upgrading from Nautobot 1.6.5 to 2.1.0, when running nautobot-server migrate, the process fails with a traceback pointing to the device-onboarding plugin failing on a null-named location/site record.

### Steps to Reproduce
nautobot-server migrate

Full traceback:

```
[nautobot@nautobot-test ~]$ nautobot-server migrate
18:25:03.843 DEBUG   nautobot.core.celery __init__.py        import_jobs_as_celery_tasks() :
  Importing system Jobs
18:25:03.844 DEBUG   nautobot.core.celery __init__.py                      register_jobs() :
  Registering job nautobot.core.jobs.ExportObjectList
18:25:03.850 DEBUG   nautobot.core.celery __init__.py                      register_jobs() :
  Registering job nautobot.core.jobs.GitRepositorySync
18:25:03.850 DEBUG   nautobot.core.celery __init__.py                      register_jobs() :
  Registering job nautobot.core.jobs.GitRepositoryDryRun
18:25:04.910 DEBUG   nautobot.core.celery __init__.py                      register_jobs() :
  Registering job nautobot_golden_config.jobs.BackupJob
18:25:04.911 DEBUG   nautobot.core.celery __init__.py                      register_jobs() :
  Registering job nautobot_golden_config.jobs.IntendedJob
18:25:04.911 DEBUG   nautobot.core.celery __init__.py                      register_jobs() :
  Registering job nautobot_golden_config.jobs.ComplianceJob
18:25:04.911 DEBUG   nautobot.core.celery __init__.py                      register_jobs() :
  Registering job nautobot_golden_config.jobs.GenerateConfigPlans
18:25:04.912 DEBUG   nautobot.core.celery __init__.py                      register_jobs() :
  Registering job nautobot_golden_config.jobs.DeployConfigPlans
18:25:04.912 DEBUG   nautobot.core.celery __init__.py                      register_jobs() :
  Registering job nautobot_golden_config.jobs.DeployConfigPlanJobButtonReceiver
18:25:04.912 DEBUG   nautobot.core.celery __init__.py                      register_jobs() :
  Registering job nautobot_golden_config.jobs.AllGoldenConfig
18:25:04.912 DEBUG   nautobot.core.celery __init__.py                      register_jobs() :
  Registering job nautobot_golden_config.jobs.AllDevicesGoldenConfig
18:25:04.913 DEBUG   nautobot.core.celery __init__.py                      register_jobs() :
  Registering job nautobot_golden_config.jobs.SyncGoldenConfigWithDynamicGroups
18:25:04.931 DEBUG   nautobot.core.celery __init__.py                      register_jobs() :
  Registering job nautobot_device_onboarding.jobs.OnboardingTask
18:25:04.938 DEBUG   nautobot.core.celery __init__.py                      register_jobs() :
  Registering job nautobot_device_lifecycle_mgmt.jobs.lifecycle_reporting.DeviceSoftwareValidationFullReport
18:25:04.938 DEBUG   nautobot.core.celery __init__.py                      register_jobs() :
  Registering job nautobot_device_lifecycle_mgmt.jobs.lifecycle_reporting.InventoryItemSoftwareValidationFullReport
18:25:04.938 DEBUG   nautobot.core.celery __init__.py                      register_jobs() :
  Registering job nautobot_device_lifecycle_mgmt.jobs.cve_tracking.GenerateVulnerabilities
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, database, dcim, django_celery_beat, django_celery_results, extras, ipam, nautobot_bgp_models, nautobot_device_lifecycle_mgmt, nautobot_device_onboarding, nautobot_golden_config, nautobot_ssot, sessions, social_django, taggit, tenancy, users, virtualization
Running migrations:
  Applying nautobot_device_onboarding.0005_migrate_site_to_location_part_2...Traceback (most recent call last):
  File "/opt/nautobot/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/opt/nautobot/lib64/python3.8/site-packages/nautobot/core/cli/__init__.py", line 53, in main
    run_app(
  File "/opt/nautobot/lib64/python3.8/site-packages/nautobot/core/runner/runner.py", line 297, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/opt/nautobot/lib64/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/nautobot/lib64/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/nautobot/lib64/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/nautobot/lib64/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/nautobot/lib64/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/nautobot/lib64/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/opt/nautobot/lib64/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/nautobot/lib64/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/nautobot/lib64/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/nautobot/lib64/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/nautobot/lib64/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/nautobot/lib64/python3.8/site-packages/nautobot_device_onboarding/migrations/0005_migrate_site_to_location_part_2.py", line 10, in migrate_to_location
    task_object.location = location_model.objects.get(name=task_object.site.name)
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by dbbtuss** [comment]
If the onboarding job history is cleared via the GUI prior to the upgrade, the problem does not happen.

**Comment by scetron** [comment]
Thanks for opening an issue. I will add this to the FAQ or somewhere in the documentation, as I believe it has come up multiple times.
