### ISSUE TITLE
Pydantic error for MTU when using develop branch

### ISSUE THREAD

**Issue by susanhooks** [nautobot/nautobot-app-device-onboarding#248]
### Environment
* Python version:  <3.11>
* Nautobot version:  <2.3.1>
* nautobot-device-onboarding version:  <4.0.1/develop branch>
* ntc-templates version: <6.1>

## Expected Behavior
Sync Network data from device as expected.

### Observed Behavior
```[2024-10-03 19:44:52,900: ERROR/ForkPoolWorker-4] Task nautobot.extras.jobs.run_job[4a132cf9-c0ac-4560-b2b8-cad9d2ffa24f] raised unexpected: ValueError("Parameters: {'device__name': 'TMA_C9407', 'name': 'GigabitEthernet0/0', 'status__name': 'Active', 'type': 'other', 'mac_address': '2C:4F:52:BC:A3:A9', 'mtu': 1500, 'mode': '', 'enabled': True, 'description': 'test', 'pk': UUID('dccc91fe-be6e-4297-9773-9231a51c6420')}")
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/nautobot_ssot/contrib/adapter.py", line 147, in _load_single_object
    diffsync_model = diffsync_model(**parameters)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for SyncNetworkDataInterface
mtu
  Input should be a valid string [type=string_type, input_value=1500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/jobs.py", line 1136, in run_job
    result = job(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/jobs.py", line 149, in __call__
    return self.run(*args, **deserialized_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/nautobot_device_onboarding/jobs.py", line 692, in run
    super().run(dryrun, memory_profiling, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/nautobot_ssot/jobs/base.py", line 330, in run
    self.sync_data(memory_profiling)
  File "/usr/local/lib/python3.11/site-packages/nautobot_ssot/jobs/base.py", line 158, in sync_data
    self.load_target_adapter()
  File "/source/nautobot_device_onboarding/jobs.py", line 594, in load_target_adapter
    self.target_adapter.load()
  File "/source/nautobot_device_onboarding/diffsync/adapters/sync_network_data_adapters.py", line 312, in load
    self._load_objects(diffsync_model)
  File "/source/nautobot_device_onboarding/diffsync/adapters/sync_network_data_adapters.py", line 33, in _load_objects
    self._load_single_object(database_object, diffsync_model, parameter_names)
  File "/usr/local/lib/python3.11/site-packages/nautobot_ssot/contrib/adapter.py", line 152, in _load_single_object
    self._handle_children(database_object, diffsync_model)
  File "/usr/local/lib/python3.11/site-packages/nautobot_ssot/contrib/adapter.py", line 162, in _handle_children
    child_diffsync_object = self._load_single_object(child, diffsync_model_child, parameter_names)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot_ssot/contrib/adapter.py", line 149, in _load_single_object
    raise ValueError(f"Parameters: {parameters}") from error
ValueError: Parameters: {'device__name': 'TEST', 'name': 'GigabitEthernet0/0', 'status__name': 'Active', 'type': 'other', 'mac_address': '2C:4F:52:BC:A3:A9', 'mtu': 1500, 'mode': '', 'enabled': True, 'description': 'test', 'pk': UUID('dccc91fe-be6e-4297-9773-9231a51c6420')}```
<!-- You can also run the hidden job 'Runs Commands on a Device to simulate SSoT Command Getter' 
on the failing device, sanitize the job output, and attach it to the issue. -->

<!--
    Describe in detail the exact steps that someone else can take to reproduce
    this bug using the current release.
-->
### Steps to Reproduce
1. Build new nautobot development environment using the dependencies in develop (specifically SSoT 3.1)
2. Run Sync Network Data on an onboarded device

I believe this issue was caused from dependency updates for pydantic and SSoT. I have a PR in progress to address this issue.

**Comment by jeffkala** [comment]
closed in #247
